INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Moravská zemská knihovna', 'http', 'kramerius.mzk.cz', 'mzk');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Národní digitální knihovna', 'http', 'krameriusndktest.mzk.cz', 'ndk');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Jihočeská vědecká knihovna v Českých Budějovicích', 'http', 'kramerius.cbvk.cz', 'cbvk');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Vědecká knihovna v Olomouci', 'http', 'kramerius.kr-olomoucky.cz', 'vkol');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Studijní a vědecká knihovna v Hradci Králové', 'http', 'kramerius4.svkhk.cz', 'svkhk');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Městská knihovna Česká Třebová', 'http', 'k5.digiknihovna.cz', 'mkct');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Severočeská vědecká knihovna v Ústí nad Labem', 'http', 'kramerius.svkul.cz', 'svkul');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ('Krajská knihovna Františka Bartoše ve Zlíně', 'http', 'dlib.kfbz.cz', 'kfbz');
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Digitální studovna Ministerstva obrany ČR", "http", "kramerius.army.cz", "dsmo");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Národní technická knihovna", "http", "kramerius.techlib.cz", "ntk");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Národní filmový archiv", "http", "library.nfa.cz", "nfa");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Krajská knihovna Karlovy Vary", "http", "k4.kr-karlovarsky.cz", "kkkv");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Univerzita Karlova v Praze - Fakulta sociálních věd", "http", "kramerius.fsv.cuni.cz", "cuni_fsv");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Knihovna Akademie věd ČR", "http", "kramerius.lib.cas.cz", "knav");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Krajská vědecká knihovna v Liberci", "http", "kramerius.kvkli.cz", "kvkli");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Knihovna Antonína Švehly", "http", "kramerius.uzei.cz", "uzei");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Mendelova univerzita v Brně", "http", "kramerius4.mendelu.cz", "mendelu");
INSERT INTO [library] ([name], [protocol], [domain], [code]) VALUES ("Městská knihovna v Praze", "http", "kramerius4.mlp.cz", "mlp");