INSERT INTO [relator] ([relator_code], [name]) VALUES ('act', 'Herec');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('adp', 'Autor adaptace, upravovatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('aft', 'Autor doslovu, tiráže atd.');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ann', 'Anotátor, autor rukopisných poznámek');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ant', 'Bibliografický předchůdce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('app', 'Žadatel, uchazeč');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('aqt', 'Autor citací nebo úryvků textu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('arc', 'Architekt');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('arr', 'Autor aranžmá');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('art', 'Umělec');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('asg', 'Nabyvatel autorského práva');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('asn', 'Přidružené jméno');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('att', 'Připisované jméno');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('auc', 'Licitátor, vyvolávač');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('aud', 'Autor dialogů');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('aui', 'Autor úvodu atd.');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('aus', 'Autor filmového scénáře atd.');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('aut', 'Autor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('bdd', 'Výtvarník vazby');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('bjd', 'Autor obálky');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('bkd', 'Knižní grafik');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('bkp', 'Výrobce knihy');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('bnd', 'Vazač');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('bpd', 'Autor exlibris');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('bsl', 'Knihkupec');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ccp', 'Autor koncepce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('chr', 'Choreograf');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('clb', 'Spolupracovník');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cli', 'Klient');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cll', 'Kaligraf');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('clt', 'Kolotypér');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cmm', 'Autor komentáře');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cmp', 'Skladatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cmt', 'Sazeč');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cnd', 'Dirigent');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cns', 'Cenzor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('coe', 'Odpůrce odvolatele');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('col', 'Sběratel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('com', 'Sestavovatel, kompilátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cos', 'Odpůrce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cot', 'Odpůrce v odvolacím řízení, odvolatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cov', 'Výtvarník desky knihy nebo ochranného pouzdra pro dokument');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cpc', 'Žadatel o udělení autorského práva');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cpe', 'Žalobce jako odpůrce odvolatele v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cph', 'Nositel autorského práva');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cpl', 'Žalobce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cpt', 'Žalobce jako odvolávající se strana v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cre', 'Tvůrce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('crp', 'Korespondent');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('crr', 'Korektor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('csl', 'Konzultant');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('csp', 'Konzultant projektu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cst', 'Návrhář kostýmů');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ctb', 'Přispěvatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cte', 'Obhájce jako odpůrce odvolatele v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ctg', 'Kartograf');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ctr', 'Kontrahent, smluvní partner');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cts', 'Obhájce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ctt', 'Obhájce jako odvolávající se strana v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cur', 'Kurátor výstavy');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('cwt', 'Autor komentáře textu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dfd', 'Obžalovaný');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dfe', 'Obžalovaný jako odpůrce odvolatele v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dft', 'Obžalovaný jako odvolávající se strana v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dgg', 'Udélovatel akademické hodnosti');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dis', 'Autor diplomové práce nebo disertace');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dln', 'Kreslíc');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dnc', 'Tanečník');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dnr', 'Dárce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dpc', 'Zobrazovaný');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dpt', 'Skladník');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('drm', 'Návrhář');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('drt', 'Režisér');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dsr', 'Výtvarník');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dst', 'Distributor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dte', 'Dedikant');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dto', 'Dedikátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('dub', 'Domnělý (pochybný) autor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('edt', 'Editor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('egr', 'Rytec');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('elt', 'Galvanotypér');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('eng', 'Technik');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('etr', 'Leptař');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('exp', 'Expert');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('fac', 'Zhotovitel faksimile');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('flm', 'Střihač');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('fmo', 'Dřívější majitel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('fnd', 'Investor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('frg', 'Falzifikátor, padělatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('-grt', 'Grafický technik');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('hnr', 'Poctěná osoba');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('hst', 'Konferenciér');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ill', 'Ilustrátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ilu', 'Iluminátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ins', 'Autor věnování');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('inv', 'Vynálezce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('itr', 'Instrumentalista, hráč na hudební nástroje');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ive', 'Dotazovaný, interviewovaný');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ivr', 'Dotazovatel, interviewující');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lbt', 'Libretista');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lee', 'Obžalovaný v odvolacím řízení (v církevním nebo námořním právu) jako odpůrce odvolatele');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lel', 'Obžalovaný (v církevním nebo námořním právu)');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('len', 'Půjčovatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('let', 'Obžalovaný v odvolacím řízení (v církevním nebo námořním právu) jako odvolávající se strana');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lie', 'Žalobce v odvolacím řízení (v církevním nebo námořním právu) jako odpůrce odvolatele');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lil', 'Žalobce (v církevním nebo námořním právu)');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lit', 'Žalobce v odvolacím řízení (v církevním nebo námořním právu) jako odvolávající se strana');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lsa', 'Zahradní a krajinný architekt');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lse', 'Původní nositel práv, licence');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lso', 'Udělovatel povolení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ltg', 'Litograf');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('lyr', 'Textař');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('mdc', 'Technik v oblasti metadat');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('mod', 'Moderátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('mon', 'Dozorčí, kontrolor)');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('mrk', 'Editor programovacích jazyků');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('mte', 'Kovorytec');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('mus', 'Hudebník');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('nrt', 'Vypravěč-komentátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('opn', 'Oponent');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('org', 'Původce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('orm', 'Organizátor akce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('oth', 'Jiná role');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('own', 'Vlastník');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pat', 'Mecenáš');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pbd', 'Šéfredaktor, odpovědný redaktor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pbl', 'Nakladatel, vydavatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pfr', 'Korektor tištěných materiálů');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pht', 'Fotograf');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('plt', 'Výrobce tiskových forem');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pop', 'Tiskař obrazu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ppm', 'Výrobce papíru');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('prc', 'Provozní technik');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('prd', 'Pracovník produkce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('prf', 'Účinkující');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('prg', 'Programátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('prm', 'Tiskař grafik');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pro', 'Producent, výrobce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('prt', 'Tiskař');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pta', 'Žadatel o udělení patentu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pte', 'Žalobce (v civilních věcech) jako odpůrce odvolatele');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ptf', 'Žalobce (v civilních věcech)');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('pth', 'Majitel patentu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ptt', 'Žalobce (v civilních věcech) jako odvolávající se strana');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rbr', 'Rubrikátor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rce', 'Technik záznamu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rcp', 'Adresát, příjemce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('red', 'Redaktor, výkonný redaktor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ren', 'Projektant architektonických ztvárnění');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('res', 'Výzkumník');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rev', 'Recenzent');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rpt', 'Reportér, zpravodaj');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rpy', 'Odpovědná strana');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rse', 'Zúčastněná osoba v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rsp', 'Zúčastněná osoba');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rst', 'Zúčastněná osoba v odvolacím řízení');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rth', 'Vedoucí výzkumného týmu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('rtm', 'Člen výzkumného týmu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('sad', 'Vědecký poradce');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('sce', 'Scénárista');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('scr', 'Písař, opisovač');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('scl', 'Sochař');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('sec', 'Sekretář, tajemník, jednatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('sgn', 'Signatář');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('sng', 'Zpěvák');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('spk', 'Spíkr');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('spn', 'Sponzor');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('srv', 'Geodet, zeměméřič');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('stn', 'Vývojový pracovník v oblasti standardizace');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('stl', 'Vypravěč pohádek, anekdot');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('str', 'Stereotypér');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('ths', 'Vedoucí diplomové práce nebo disertace');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('trc', 'Přepisovač');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('trl', 'Překladatel');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('tyd', 'Návrhář písma');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('tyg', 'Typograf');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('voc', 'Pěvec');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('wam', 'Autor textu doprovodného materiálu');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('wdc', 'Dřevořezbář');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('wde', 'Dřevorytec');
INSERT INTO [relator] ([relator_code], [name]) VALUES ('wit', 'Svědek');
